name: Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  # conditional envs
  ACT_IS_SNAPSHOT: ${{ github.event_name == 'workflow_dispatch' && startsWith(github.ref, 'refs/heads/release/') == false }}
  ACT_IS_BETA: ${{ github.event_name == 'workflow_dispatch' && startsWith(github.ref, 'refs/heads/release/') == true }}
  ACT_IS_RELEASE: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') == true }}
  # workflow envs
  ACT_NODE_VERSION: 12.x
  ACT_GITHUB_EVENT_NAME: ${{ github.event_name }}
  ACT_GITHUB_REF: ${{ github.ref }}
  # updated in "configure pipeline" step
  ACT_RELEASE_VERSION: ''

jobs:
  npm-publish:
    runs-on: [self-hosted, vmslave]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node (publish)
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.ACT_NODE_VERSION }}
          registry-url: ${{ secrets.ORG_CORE_NEXUS_NPM_HOSTED_WEFOX_URL }}
      - name: Configure pipeline
        run: |
          if [[ ${ACT_IS_SNAPSHOT} == "true" ]]; then
            ACT_RELEASE_VERSION=$(node -p "require('./package.json').version")-snapshot.$(git rev-parse --short HEAD)
          elif [[ ${ACT_IS_BETA} == "true" ]]; then
            ACT_RELEASE_VERSION=$(node -p "require('./package.json').version")-beta.$(date +'%s')
          elif [[ ${ACT_IS_RELEASE} == "true" ]]; then
            ACT_RELEASE_VERSION=${ACT_GITHUB_REF#refs/tags/}
          else
            echo "Unexpected error in configuration pipeline step"
            exit 1
          fi

          echo "ACT_RELEASE_VERSION=${ACT_RELEASE_VERSION}" >> ${GITHUB_ENV}
      - name: Bump version
        run: npm --no-git-tag-version --allow-same-version version "${ACT_RELEASE_VERSION}"
      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ORG_CORE_NEXUS_NPM_TOKEN }}
        run: npm publish
